name: Build & Push Docker Image

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # required for Workload Identity Federation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/746287134716/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deploy@project-feb6df0e-9749-4925-b4e.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image via Cloud Build
        run: |
          gcloud builds submit \
            --tag asia-southeast1-docker.pkg.dev/project-feb6df0e-9749-4925-b4e/market-repo/market-breadth:latest \
            --region asia-southeast1 \
            --project project-feb6df0e-9749-4925-b4e

      - name: Update Cloud Run Job image
        run: |
          gcloud run jobs update market-breadth-job \
            --image asia-southeast1-docker.pkg.dev/project-feb6df0e-9749-4925-b4e/market-repo/market-breadth:latest \
            --region asia-southeast1 \
            --project project-feb6df0e-9749-4925-b4e
